
<!-- qcard03 팝업 -->
<div class="layer_body pop_qcard03" id="pop_qcard03" aria-hidden="true" role="dialog">
	<div class="layer_container">
		<div class="layer_wrap">
			<div class="layer_header">
				<button onclick="layerClose('pop_qcard03');return false;" class="layer_close manualfn">닫기</button>
			</div>
			<div class="layer_content">
				<p></p>
				<div>"2021년 BMW LADIES CHAMPIONSHIP은 정부의 사회적 거리두기와 안전한 대회 운영을 위하여 무관중 대회로 진행될 예정입니다."</div>
				<div class="vod_table">
					<div class="tit">방송 중계 일정</div>
					<div class="half-div">
						<dl>
							<dt>JTBC GOLF</dt>
							<dd>
								<span>10월21일 목요일: 11:00 - 16:00 (생중계)</span>
								<span>10월22일 금요일: 11:00 - 16:00 (생중계)</span>
								<span>10월23일 토요일: 11:00 - 16:00 (생중계)</span>
								<span>10월24일 일요일: 11:00 - 16:00 (생중계)</span>
							</dd>
						</dl>
						<dl>
							<dt>JTBC</dt>
							<dd>
								<span>10월24일 일요일: 14:00 - 16:00 (생중계)</span>
							</dd>
						</dl>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--// qcard03 팝업 -->
<div class="footer @@footype">
	<div class="partners">
		<ul class="logos top">
			<li class="part1"><img src="../assets/images/common/partner_logo01.gif" alt="" /></li>
			<li class="part4"><img src="../assets/images/common/partner_logo02.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo03.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo04.gif" alt="" /></li>
			<li class="part4"><img src="../assets/images/common/partner_logo05.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo06.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo07.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo08.gif" alt="" /></li>
		</ul>
	</div>
	<div class="copyright">
		<div class="row">
			ⓒ BMW Korea 2019
		</div>
	</div>
</div>
