
<!-- qcard03 팝업 -->
<div class="layer_body pop_qcard03" id="pop_qcard03" aria-hidden="true" role="dialog">
	<div class="layer_container">
		<div class="layer_wrap">
			<div class="layer_header">
				<button onclick="layerClose('pop_qcard03');return false;" class="layer_close manualfn">닫기</button>
			</div>
			<div class="layer_content">
				<p></p>
				<div>"2021년 BMW LADIES CHAMPIONSHIP은 정부의 사회적 거리두기와 안전한 대회 운영을 위하여 무관중 대회로 진행될 예정입니다."</div>
				<!-- <p class="desktop"><a href="http://ticket.interpark.com/Ticket/Goods/GoodsInfo.asp?GoodsCode=19010119" target="_blank" onclick="layerClose('pop_qcard03');"><img src="../assets/images/contents/pop_qcard03_img.jpg" alt=""></a></p>
				<p class="mobile"><a href="http://ticket.interpark.com/Ticket/Goods/GoodsInfo.asp?GoodsCode=19010119" target="_blank" onclick="layerClose('pop_qcard03');"><img src="../assets/images/contents/mpop_qcard03_img.jpg" alt=""></a></p> -->
			</div>
		</div>
	</div>
</div>
<!--// qcard03 팝업 -->
<div class="footer @@footype">
	<div class="partners">
		<ul class="logos top">
			<li class="part1"><img src="../assets/images/common/partner_logo01.gif" alt="" /></li>
			<li class="part2"><img src="../assets/images/common/partner_logo02.gif" alt="" /></li>
			<li class="part4"><img src="../assets/images/common/partner_logo04.gif" alt="" /></li>

			<li><img src="../assets/images/common/partner_logo09.gif" alt="" /></li>
			<!-- <li><img src="../assets/images/common/partner_logo11.gif" alt="대한항공" /></li> -->
			<li><img src="../assets/images/common/partner_logo10.gif" alt="" /></li>
			<li class="part6"><img src="../assets/images/common/partner_logo06.gif" alt="" /></li>
		</ul>
	</div>
	<div class="copyright">
		<div class="row">
			ⓒ BMW Korea 2019
		</div>
	</div>
</div>
