
<div class="header">
	<div class="row">
		<div class="mo_menu">
			<a href="#" class="mbtn"><span class="a11y">모바일메뉴</span></a>
		</div>
		<div class="top_navi">
			<ul class="navi">
				<li class="p_bullet">
					<a href="information.html" class="tab">대회 안내</a>
				</li>
				<li class="p_bullet">
					<a href="place.html" class="tab">장소 소개</a>
				</li>
				<li class="p_bullet">
					<a href="#" onclick="layerOpen('pop_qcard03');return false;" class="tab">티켓 정보</a>
					<!-- <a href="tickets.html" class="tab">티켓 정보</a> -->
				</li>
				<li class="p_bullet">
					<a href="partners.html" class="tab">파트너</a>
				</li>
			</ul>
		</div>
		<div class="lang">
			<p class="now"><a href="main.html">한국어</a></p>
			<p><a href="../en/html/main.html">English</a></p>
		</div>

		<div class="mtop_navi">
			<div class="inner">
				<ul class="navi" id="accor">
					<li class="p_bullet">
						<a href="information.html" class="tab">대회 안내</a>
					</li>
					<li class="p_bullet">
						<a href="#" onclick="subMenuShow(this)" class="tab">장소 소개</a>
						<div class="subdepth">
							<ul class="submenu">
								<li><a href="place.html">장소 소개</a></li>
								<li><a href="course.html">코스 가이드</a></li>
								<li><a href="area.html">주요 시설</a></li>
								<li><a href="map.html">찾아오시는 길</a></li>
							</ul>
						</div>
					</li>
					<li class="p_bullet">
						<a href="#" onclick="layerOpen('pop_qcard03');return false;" class="tab">티켓 정보</a>
						<!-- <a href="tickets.html" class="tab">티켓 정보</a> -->
					</li>
					<li class="p_bullet">
						<a href="partners.html" class="tab">파트너</a>
					</li>
				</ul>
				<div class="sub_depth menu01">
					<p class="title"><a href="#" onclick="mtopMenuHide();return false;">대회 안내</a></p>
					<ul class="menu">
						<li><a href="information.html">대회 안내</a></li>
						<li><a href="place.html">장소 소개</a></li>
						<li><a href="player.html">참가 선수</a></li>
						<li><a href="#">찾아오시는 길</a></li>
					</ul>
				</div>
			</div>


		</div>
		<h1 class="logo"><a href="main.html"><span class="a11y">Bmw Korea</span></a></h1>
    <p class="bmw-claim">Sheer Driving <span>Pleasure</span></p>
	</div>
</div>

