	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-63692970-1"></script>
	<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());

	gtag('config', 'UA-63692970-1');
	</script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta http-equiv="Content-Type" content="text/html; CHARSET=utf-8" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta name="description" content="@@metaDesc" />
	<meta property="og:type" content="website">
	<meta property="og:title" content="@@title"/>
	<meta property="og:description" content="@@metaDesc"/>
	<meta property="og:image" content="@@webRoot/assets/images/contents/vod_bg.jpg"/>

	<meta name="twitter:card" content="summary">
	<meta name="twitter:title" content="@@title">
	<meta name="twitter:description" content="@@metaDesc">
	<meta name="twitter:image" content="@@webRoot/assets/images/contents/vod_bg.jpg">

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
	<!-- <meta name="viewport" content="width=device-width, user-scalable=no, width=1024"> -->
	<title>@@title</title>
	<link rel="icon" href="@@webRoot/assets/images/common/favicon.ico" type="image/x-icon">
	<link rel="stylesheet" href="@@webRoot/assets/css/ui.css" />
	<script type="text/javascript" src="@@webRoot/assets/js/jquery-1.11.2.min.js"></script>
