<div class="footer @@footype">
	<div class="partners">
		<ul class="logos top">
			<li class="part1"><img src="../assets/images/common/partner_logo01.gif" alt="" /></li>
			<li class="part4"><img src="../assets/images/common/partner_logo02.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo03.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo04.gif" alt="" /></li>
			<li class="part4"><img src="../assets/images/common/partner_logo05.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo06.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo07.gif" alt="" /></li>
			<li><img src="../assets/images/common/partner_logo08.gif" alt="" /></li>
		</ul>
	</div>
	<div class="copyright">
		<div class="row">
			ⓒ BMW Korea 2019
		</div>
	</div>
</div>
